Repository Trip-Full-Accel/tfa-FE, pull requests merged in 2022-12, with the labels that each got.

#3 Update: footer.css & slider change #2
  src/components/slide/Slider.tsx
  src/static/footer.css
Labels: feature

#5 Fix:TourList components reunion to Maps components #4
  src/components/map/Maps.tsx
  src/components/map/TourList.tsx
Labels: fix

#11 Update & Fix: mainpage ui change & startbtn scroll add & video tag controllist fixed #9
  src/components/Template.tsx
  src/components/main/Main.tsx
  src/components/map/Maps.tsx
  src/static/main.css
Labels: fix

#16 Feat: login modal 80% nav 80% #15
  package-lock.json
  package.json
  public/img/login.webp
  src/components/Template.tsx
  src/components/header/Header.css
  src/components/header/Header.tsx
  src/components/header/HeaderList.tsx
  src/components/main/Main.tsx
  src/static/loginBtn.css
  src/static/modal.css
  src/static/sidebars.css
Labels: feat

#18 Feat: navbar create & main div fix & login modal create #17
  src/components/MyPage/UserInfo.tsx
  src/components/header/Header.css
  src/components/header/Header.tsx
  src/components/header/HeaderList.tsx
  src/components/header/modal.css
  src/components/infomation/TfaInfo.tsx
  src/components/main/Main.tsx
  src/components/photo/Photo.tsx
  src/components/slide/Slider.tsx
  src/components/topbtn/Topbtn.tsx
  src/static/main.css
  src/static/modal.css
Labels: develop

#20 Fix,Update: NavBar fix & Login Modal img Update & Silde Fix #19
  public/img/123.png
  public/img/login/login1.webp
  public/img/login/login2.png
  public/img/login/login3.jpg
  public/img/login/login4.jpg
  public/img/login/login5.jpg
  public/img/login/login6.jpg
  public/img/login/login7.jpg
  public/img/login/login8.jpg
  public/img/login2.png
  public/polygon/polygon.json
  src/components/Template.tsx
  src/components/header/Header.css
  src/components/header/Header.tsx
  src/components/header/HeaderList.tsx
  src/components/header/modal.css
  src/components/infomation/TfaInfo.tsx
  src/components/main/Main.tsx
  src/components/photo/Photo.tsx
  src/components/polygon/chart.jsx
  src/components/slide/LoginSlider.tsx
  src/components/slide/Slider.tsx
  src/components/slide/silder.css
  src/route/TFARoute.tsx
  src/static/template.css
Labels: fix, update

#25 Fix: video div fix & nav zindex fix & delete scrollbar & organization div, css & image extension change #24
  package.json
  public/img/login.webp
  public/img/login/login1.jpg
  public/img/login/login1.webp
  public/img/login/login2.jpg
  public/img/login/login2.png
  public/img/login2.png
  public/img/topbtn.png
  public/index.html
  src/App.css
  src/components/MyPage/MyPage.tsx
  src/components/MyPage/TravelCost.tsx
  src/components/MyPage/TravelRoute.tsx
  src/components/MyPage/UserInfo.tsx
  src/components/Template.tsx
  src/components/header/Header.css
  src/components/header/Header.tsx
  src/components/header/HeaderList.tsx
  src/components/header/modal.css
  src/components/infomation/TfaInfo.tsx
  src/components/login/LoginModal.tsx
  src/components/main/Main.tsx
  src/components/map/Maps.tsx
  src/components/map/TourList.tsx
  src/components/photo/Photo.tsx
  src/components/polygon/chart.jsx
  src/components/slide/LoginSlider.tsx
  src/components/slide/Slide.tsx
  src/components/slide/silde.css
  src/components/topbtn/Topbtn.tsx
  src/http/customAxios.ts
  src/index.css
  src/index.tsx
  src/route/TFARoute.tsx
  src/setupTests.js
  src/setupTests.ts
  src/static/bootmodal.css
  src/static/login.css
  src/static/loginBtn.css
  src/static/main.css
  src/static/mainGoToMap.css
  src/static/modal.css
  src/static/slider.css
  src/static/template.css
  src/static/test.css
  src/store/counter/counterReducer.ts
Labels: fix, style

#29 Feat: KakaoLogin & NaverLogin complete #28
  package-lock.json
  public/index.html
  src/components/Template.tsx
  src/components/header/Header.tsx
  src/components/kakao.tsx
  src/components/kakaoRedirect.tsx
  src/components/lgGoogle.tsx
  src/components/naver.tsx
  src/react-app-env.d.ts
  src/route/TFARoute.tsx
  src/store/kakaoTokenTest/tokenTest.ts
  src/store/store.ts
Labels: feat

#33 Feat : styled components almost done
  src/components/board/board.tsx
  src/components/footer/Footer.tsx
  src/components/main/Main.tsx
  src/components/map/Maps.tsx
  src/components/slide/Slide.tsx
  src/components/slide/slider.css
  src/components/topbtn/Topbtn.tsx
  src/static/Maps.css
  src/static/all.css
  src/static/footer.css
  src/static/login.css
  src/static/main.css
  src/static/mainGoToMap.css
  src/static/topbtn.css
Labels: feat

#35 Style: styled components complete #34
  src/components/header/Header.css
  src/components/header/Header.tsx
Labels: style

#37 Develop, Fix: Board create done & Board redux setting & Topbtn fix #36
  src/components/board/Regist.tsx
  src/components/board/board.tsx
  src/components/topbtn/Topbtn.tsx
  src/route/TFARoute.tsx
  src/store/board/boardReducer.ts
  src/store/board/boardType.ts
  src/store/store.ts
Labels: develop, fix

#41 Develop, Update : board axios test 90% done #40
  src/components/board/Regist.tsx
  src/components/board/board.tsx
  src/http/customAxios.ts
  src/logo.svg
  src/store/board/boardReducer.ts
  src/store/board/boardType.ts
  src/store/getMappingTest/getMappingTestReducer.ts
  src/store/store.ts
Labels: develop, update

#44 Develop & Feat & Fix & Style & Update : account page done & navbar style change & loginimg fix & logo, main button change #43
  public/img/TFAlogo.png
  src/components/account/account.tsx
  src/components/header/Header.tsx
  src/components/header/HeaderList.tsx
  src/route/TFARoute.tsx
Labels: develop, fix, style

#49 Feature/fe 1215
  package-lock.json
  package.json
  src/components/forgotPw/forgotPw.tsx
  src/components/header/Header.tsx
  src/components/main/MainBtn.tsx
  src/route/TFARoute.tsx
Labels: develop

#52 Feature/account input
  package-lock.json
  package.json
  src/components/MyPage/MyPage.tsx
  src/components/account/account.tsx
  src/components/board/board.tsx
  src/components/board/boardList.tsx
  src/components/forgotPw/forgotPw.tsx
  src/components/header/Header.tsx
  src/components/pagenation/Pagenation.tsx
  src/store/user/userReducer.ts
  src/store/user/userType.ts
Labels: git.....

#54 Feat : user find password done #53
  public/img/boardimg.png
  src/components/board/board.tsx
  src/components/board/boardList.tsx
  src/components/forgotPw/forgotPw.tsx
  src/store/user/userReducer.ts
  src/store/user/userType.ts
Labels: feat

#57 Feat, Fix : main header Login transform and mypage linkTo done, findpw input fix #56
  src/components/MyPage/MyPage.tsx
  src/components/account/account.tsx
  src/components/board/Regist.tsx
  src/components/board/board.tsx
  src/components/board/boardList.tsx
  src/components/forgotPw/forgotPw.tsx
  src/components/header/Header.tsx
  src/components/map/Maps.tsx
  src/store/user/userReducer.ts
  src/store/user/userType.ts
Labels: fix, feat

#60 Feat : board search almost done #59
  package-lock.json
  package.json
  src/components/board/board.tsx
  src/components/board/boardList.tsx
  src/components/forgotPw/forgotPw.tsx
  src/components/header/Header.tsx
  src/store/board/boardReducer.ts
  src/store/board/boardType.ts
  src/store/user/userReducer.ts
Labels: feat

#63 Develop : board search complete #62
  package.json
  src/components/board/board.tsx
  src/components/board/boardListTest.tsx
  src/components/pagenation/Pagenation.css
  src/components/pagenation/Pagenation.tsx
  src/components/pagenation/boardList.tsx
  src/store/board/boardReducer.ts
  src/store/footerName/footerReducer.ts
Labels: develop

#65 Develop: tfaInfo almost done #64
  package-lock.json
  package.json
  public/img/chart.PNG
  public/index.html
  src/components/MyPage/MyPage.css
  src/components/MyPage/MyPage.tsx
  src/components/MyPage/useMoveScroll.tsx
  src/components/Template.tsx
  src/components/infomation/TfaInfo.tsx
  src/components/topbtn/Topbtn.tsx
  src/route/TFARoute.tsx
  src/static/all.css
  src/static/font/KNPSBandali.otf
  src/static/font/font.css
Labels: develop

#67 Feat : maps connect done #66
  package-lock.json
  src/components/board/boardListTest.tsx
  src/components/infomation/TfaInfo.tsx
  src/components/map/Maps.tsx
  src/components/pagenation/Pagenation.css
  src/components/pagenation/boardList.tsx
  src/http/customAxiosForMap.ts
  src/store/map/mapReducer.ts
  src/store/map/mapType.ts
  src/store/store.ts
Labels: feat

#69 Develop : map draggalbe start #68
  package-lock.json
  package.json
  src/components/board/board.tsx
  src/components/header/Header.tsx
  src/components/infomation/TfaInfo.tsx
  src/components/map/Maps.tsx
  src/components/map/Points.tsx
  src/components/pagenation/Pagenation.css
  src/components/pagenation/boardList.tsx
  src/components/photo/Photo.tsx
  src/components/slide/Slide.tsx
  src/components/topbtn/Topbtn.tsx
  src/http/customAxiosForMap.ts
  src/store/map/mapReducer.ts
Labels: develop

#71 Fix & Update : topbtn fix, a tag fix, boardlist fix, tfaInfo update #70
  package-lock.json
  package.json
  src/components/board/board.tsx
  src/components/header/Header.tsx
  src/components/header/modal.css
  src/components/infomation/TfaInfo.tsx
  src/components/map/Maps.tsx
  src/components/map/Points.tsx
  src/components/map/TourList.tsx
  src/components/map/maptest.tsx
  src/components/pagenation/Pagenation.css
  src/components/pagenation/boardList.tsx
  src/http/customAxios.ts
  src/http/customAxiosForMap.ts
  src/route/TFARoute.tsx
Labels: fix, update

#78 Fix : Board Crud Test Done & alert add #77
  package-lock.json
  src/components/board/Regist.tsx
  src/components/board/board.tsx
  src/components/board/boardDetail.tsx
  src/components/board/boardModify.tsx
  src/components/main/Main.tsx
  src/components/pagenation/boardList.tsx
  src/http/customAxiosForMap.ts
  src/route/TFARoute.tsx
  src/store/board/boardReducer.ts
  src/store/board/boardType.ts
  src/store/reduxTest/reduxTestReducer.ts
  src/store/reduxTest/reduxTestType.ts
  src/store/store.ts
Labels: fix

#81 Develop, feat, fix, style : date-range develop & feat main modal & fix: mainbtn, maps, style: all.css change #80
  package-lock.json
  package.json
  src/components/header/Header.tsx
  src/components/infomation/Info.tsx
  src/components/infomation/TfaInfo.tsx
  src/components/infomation/info.css
  src/components/main/Main.tsx
  src/components/map/Maps.tsx
  src/components/map/Points.tsx
  src/components/map/maptest.tsx
  src/components/photo/Photo.tsx
  src/components/slide/AreaName.tsx
  src/components/slide/BusanSlide.tsx
  src/components/slide/DaeguSlide.tsx
  src/components/slide/DaejeonSlide.tsx
  src/components/slide/GangwondoSlide.tsx
  src/components/slide/JejuSlide.tsx
  src/components/slide/PohangSlide.tsx
  src/components/slide/SeoulSlide.tsx
  src/components/slide/Slide.tsx
  src/components/slide/YeosuSlide.tsx
  src/static/all.css
Labels: develop, fix, feat, style

#82 Develop, Fix : Board Img upload & react-quill text editor complete #79
  package-lock.json
  package.json
  public/index.html
  src/components/board/Regist.tsx
  src/components/board/board.css
  src/components/board/boardDetail.tsx
  src/components/board/boardEditor.tsx
  src/components/board/boardModify.tsx
  src/components/main/Main.tsx
  src/route/TFARoute.tsx
  src/store/board/boardType.ts
  src/store/image/imgReducer.ts
  src/store/image/imgType.ts
  src/store/store.ts
Labels: develop, fix

#86 Develop, Fix : Maps page data load complete & draggable almost done #83
  package-lock.json
  package.json
  public/img/mark.png
  public/img/mark2.png
  public/index.html
  src/App.css
  src/components/board/Regist.tsx
  src/components/map/Maps.tsx
  src/components/map/Points.tsx
  src/components/map/maptest.tsx
  src/components/map/maptest2.tsx
  src/components/map/maptest3.jsx
  src/components/map/maptest4.tsx
  src/http/customAxiosForMap.ts
  src/route/TFARoute.tsx
  src/static/all.css
  src/store/map/mapReducer.ts
  src/store/map/mapType.ts
Labels: develop, fix

#85 Feat, Fix : main calender done and div fix, all.css fix, font.css add number, boardlist fix #84
  package-lock.json
  package.json
  public/img/calender.png
  public/index.html
  src/App.css
  src/components/main/Main.tsx
  src/components/pagenation/boardList.tsx
  src/components/slide/AreaName.tsx
  src/static/font/font.css
Labels: fix, feat

#88 Develop, fix, feat : suggestpage made, board fix, dateT&title done, navbar change
  package-lock.json
  package.json
  public/index.html
  src/components/board/Regist.tsx
  src/components/board/boardDetail.tsx
  src/components/header/Header.tsx
  src/components/main/Main.tsx
  src/components/map/Maps.tsx
  src/components/pagenation/boardList.tsx
  src/components/suggest/suggest.tsx
  src/route/TFARoute.tsx
  src/static/font/font.css
Labels: develop, fix, feat

#92 Fix : boardList, boardDetail, map div change #91
  src/components/board/board.tsx
  src/components/board/boardDetail.tsx
  src/components/main/Main.tsx
  src/components/map/Maps.tsx
  src/components/map/Points.tsx
  src/components/map/maptest.tsx
  src/components/map/maptest3.jsx
  src/components/map/maptest4.tsx
  src/components/pagenation/boardList.tsx
Labels: fix

#95 Fix : board detail page fix #94
  src/components/board/boardDetail.tsx
  src/components/chatbot/ActionProvider.jsx
  src/components/chatbot/ActionProvider.tsx
  src/components/chatbot/MessageParser.tsx
  src/components/chatbot/chatbot.css
  src/components/chatbot/config.js
  src/components/header/Header.tsx
  src/components/main/Main.tsx
  src/components/map/maptest.tsx
  src/store/board/boardReducer.ts
  src/store/board/boardType.ts
  src/store/map/mapType.ts
  src/store/user/userReducer.ts
Labels: fix

#96 merge
  public/img/chatbot.png
  src/components/header/Header.tsx
  src/components/main/Main.tsx
  src/components/topbtn/Topbtn.tsx
Labels: git.....

#97 chatbot img change
  src/components/chatbot/chatbot.css
  src/components/chatbot/config.js
  src/components/header/Header.tsx
Labels: fix

#99 for merge Feature/fe 1223
  package-lock.json
  package.json
  public/img/calendar.png
  src/components/MyPage/MyPage.tsx
  src/components/Template.tsx
  src/components/header/Header.tsx
  src/components/main/Main.tsx
  src/components/suggest/suggest.css
  src/components/suggest/suggest.tsx
  src/route/TFARoute.tsx
  src/static/font/font.css
Labels: git.....

#104 Fix, Style, Feat : Topbtn, Chatbot switch, Footer style change, suggest tab done, translate style change, Mypage Homebtn done
  public/img/translate/EN.png
  public/img/translate/KO.png
  src/components/MyPage/MyPage.tsx
  src/components/board/boardDetail.tsx
  src/components/board/boardListTest.tsx
  src/components/chatbot/chatbot.css
  src/components/chatting/chatting.tsx
  src/components/footer/Footer.tsx
  src/components/header/Header.tsx
  src/components/main/Main.tsx
  src/components/suggest/suggest.css
  src/components/topbtn/Topbtn.tsx
  src/components/translate/translate.tsx
  src/language/en.json
  src/language/ko.json
  src/route/TFARoute.tsx
  src/static/font/KNPSKkomi.otf
  src/static/font/font.css
Labels: fix, feat, style

#105 Feat : translate 70% done , BE peristalsis 50% done, music div done #102
  src/components/MyPage/MyPage.css
  src/components/MyPage/MyPage.tsx
  src/components/footer/Footer.tsx
  src/components/header/Header.tsx
  src/components/kakaoRedirect.tsx
  src/components/main/Main.tsx
  src/components/map/maptest.tsx
  src/components/music/music.css
  src/components/music/music.tsx
  src/components/translate/translate.tsx
  src/http/customAxios.ts
  src/http/customAxiosForMap.ts
  src/language/en.json
  src/language/ko.json
  src/store/map/mapReducer.ts
  src/store/map/mapType.ts
  src/store/user/userReducer.ts
Labels: feat

#108 Feat, Style : footer icon done, boardDetail, boardRegist style change topbtn,chatbot style change #106
  src/components/MyPage/MyPage.tsx
  src/components/account/acc.css
  src/components/board/Regist.tsx
  src/components/board/board.css
  src/components/board/board.tsx
  src/components/board/boardDetail.tsx
  src/components/footer/Footer.tsx
  src/components/header/Header.tsx
  src/components/main/Main.tsx
  src/components/topbtn/Topbtn.tsx
  src/http/customAxios.ts
  src/http/customAxiosForMap.ts
  src/store/map/mapReducer.ts
Labels: feat, style

#111 Feat, Fix, style : BoardDetail done, boardRegist done, boardList done btn changed, delete account -> mypage #110
  package-lock.json
  package.json
  src/components/MyPage/MyPage.tsx
  src/components/board/Regist.tsx
  src/components/board/board.css
  src/components/board/board.tsx
  src/components/board/boardDetail.tsx
  src/components/header/Header.css
  src/components/header/Header.tsx
  src/components/main/Main.tsx
  src/components/pagenation/boardList.tsx
  src/components/translate/translate.tsx
  src/language/ko.json
  src/static/all.css
Labels: fix, feat, style

#122 Develop, Feat, Fix, Style: suggest done, font done, translate almost done #121
  src/components/board/board.tsx
  src/components/board/boardDetail.tsx
  src/components/header/Header.tsx
  src/components/main/Main.tsx
  src/components/photo/Photo.tsx
  src/components/slide/AreaName.tsx
  src/components/slide/BusanSlide.tsx
  src/components/slide/DaeguSlide.tsx
  src/components/slide/DaejeonSlide.tsx
  src/components/slide/GangwondoSlide.tsx
  src/components/slide/GyeonggidoSlide.tsx
  src/components/slide/GyeongsangbukdoSlide.tsx
  src/components/slide/JejuSlide.tsx
  src/components/slide/SeoulSlide.tsx
  src/components/suggest/Threed.tsx
  src/components/suggest/suggest.css
  src/components/suggest/suggest.tsx
  src/components/suggest/three.jsx
  src/http/customAxios.ts
  src/http/customAxiosForMap.ts
  src/language/en.json
  src/language/ko.json
  src/route/TFARoute.tsx
  src/static/all.css
  src/static/font/font.css
Labels: develop, fix, feat, style

#124 Feat:central of the travel area #123
  src/components/map/Maps.tsx
Labels: feat
